"""empty message

Revision ID: 668943f771d5
Revises: 
Create Date: 2017-06-22 22:40:49.388418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668943f771d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.create_table('users',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('todolist')
    # ### end Alembic commands ###
