"""change table name

Revision ID: e8c25a67fc4f
Revises: 668943f771d5
Create Date: 2017-06-22 22:55:41.332226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8c25a67fc4f'
down_revision = '668943f771d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.drop_table('todolist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('taskId', sa.INTEGER(), server_default=sa.text(u'nextval(\'"todolist_taskId_seq"\'::regclass)'), nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('taskId', name=u'todolist_pkey')
    )
    op.drop_table('todolists')
    # ### end Alembic commands ###
